name: Daily YouTube Trending Fetch

on:
  schedule:
    - cron: "30 0 * * *"   # 00:30 UTC = 6:00 AM IST
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.10"

    - name: Install dependencies
      run: pip install -r requirements.txt

    # PULL BEFORE RUNNING SCRIPT
    - name: Pull latest changes
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git pull --rebase origin main || echo "Nothing to pull"

    - name: Run script
      working-directory: ./scripts
      env:
        YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}
      run: python main.py


    - name: Commit new data
      run: |
        git add data/
        git commit -m "Daily update - $(date '+%Y-%m-%d')" || echo "No changes to commit"
        git push origin main || echo "No changes to push"
